[workspace]
members = [
    "imager",
]

exclude = [
    "imager-video",
    "imager-server",
    "classifier",
]

[profile.release]
codegen-units = 1
lto = true
strip = true

[profile.dev]
opt-level = 3
lto = true
